# Generated by Django 5.0.3 on 2024-03-11 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='MagnitudeMW',
        ),
    ]
