# Generated by Django 3.2.19 on 2024-03-25 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image2',
            field=models.ImageField(blank=True, default='default1.jpg', upload_to='image_ml'),
        ),
    ]
