# Generated by Django 5.0.3 on 2024-03-13 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_post_magnitudemw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
    ]
