# Generated by Django 5.0.3 on 2024-03-25 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0003_post_file3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='MagnitudeMW',
        ),
        migrations.RemoveField(
            model_name='post',
            name='file3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='image2',
        ),
        migrations.AddField(
            model_name='post',
            name='aaaaaaaaa',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
