# Generated by Django 5.0.3 on 2024-03-25 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0004_remove_post_magnitudemw_remove_post_file3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='aaaaaaaaa',
        ),
    ]
