# Generated by Django 5.0.3 on 2024-03-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0004_remove_post_file3_remove_post_image2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Magnitude',
        ),
    ]
