# Generated by Django 5.0.3 on 2024-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0005_remove_post_aaaaaaaaa'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='MagnitudeMW',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
