# Generated by Django 5.0.3 on 2024-03-13 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0006_post_magnitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='MagnitudeMW',
            field=models.CharField(max_length=100),
        ),
    ]
