# Generated by Django 5.0.3 on 2024-03-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0007_alter_post_magnitudemw'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='MagnitudeMW',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
