# Generated by Django 3.2.19 on 2024-03-10 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0007_stations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Gap',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Magnitude',
        ),
    ]
