# Generated by Django 3.2.19 on 2024-03-10 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0008_auto_20240311_0242'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Magnitude22',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
