# Generated by Django 5.0.3 on 2024-03-13 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0009_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='MagnitudeMW',
        ),
    ]
