# Generated by Django 5.0.3 on 2024-03-23 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0011_post_magnitudemw'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='MagnitudeMW',
        ),
    ]
