# Generated by Django 3.2.19 on 2024-03-23 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testdb', '0009_post_magnitude22'),
        ('testdb', '0013_post_magnitudemw'),
    ]

    operations = [
    ]
